default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list-again_development

test:
  <<: *default
  database: rails-watch-list_test
